@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.accessToken}}
# @name create_account
POST {{baseUrl}}/auth/register
Content-Type: application/json

{ 
  "name": "Jm admin",
  "email": "jmeletromotores-admin@hotmail.com",
  "password": "1609Jota@",
  "role": "ADMIN"
}

###

# @name authenticate
POST {{baseUrl}}/employee
Content-Type: application/json

{
  "name": "Miriam Romualdo",
  "position": "Administrativo",
  "imgUrl": "https://placehold.co/600x400/png",
  "rfid": "0001702628",
  "journeyId": "dbc94b6d-9b56-4f21-a1af-c2e69faba74d"
}

###

POST {{baseUrl}}/employee
Content-Type: application/json

{
  "name": "Gustavo Santos",
  "position": "Desenvolvedor Front-end",
  "imgUrl": "http",
  "rfid": "9234567813",
  "journeyId": "47cbae4a-822a-490d-95b2-7ebb88482e15"
}

###
GET {{baseUrl}}/report/pdf/2024-05-01T23:59:00.000Z/2024-05-31T23:59:00.000Z/0001702628
Content-Type: application/json

{
  "rfid": "9234567813",
  "startDate":  "2024-04-01T23:59:00.000Z",
  "endDate": "2024-04-31T23:59:00.000Z"
}

###

###
POST {{baseUrl}}/abono
Content-Type: application/json

{
  "rfid": "1234567811",
  "date":  "2024-04-05T00:00:00.000Z",
  "reason": "Ano novo"
}
###

# @name authenticate
POST {{baseUrl}}/journey
Content-Type: application/json

{
  "name": "Jornada padrão",
  "start_date": "08:00",
  "end_date": "18:00",
  "start_date_toleranceDelay": "08:10",
  "end_date_toleranceExtraTime": "18:10",
  "lunch_time_tolerance": 60,
  "start_date_toleranceExtraTime": "07:50",
  "friday_end_date": "17:00",
  "friday_end_date_toleranceExtraTime": "17:10"
}

###



POST  {{baseUrl}}/schedules
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "rfid": "1234567813",
  "date": "2024-04-21T10:00:00.000Z",
  "clockedIn": "2024-04-21T13:00:00.000Z"
}

###

###



PUT  {{baseUrl}}/schedules/lunchend/delete/b37338f0-60ee-41eb-8e1c-5297cfc2bf24
Content-Type: application/json
Authorization: Bearer {{authToken}}


###

PUT  {{baseUrl}}/schedules/lunchstart
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "rfid": "1234567813",
  "lunchStart": "2024-04-21T15:00:00.000Z"
}

###

PUT  {{baseUrl}}/attendances/776b869f-b74b-4a34-9cca-5eb1c90c179a
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "rfid": "1234567811",
  "newTime": "2024-04-20T14:00:00.000Z"
}

###

PUT  {{baseUrl}}/schedules/clockedout/b37338f0-60ee-41eb-8e1c-5297cfc2bf24
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "rfid": "1234567895",
  "clockedOut": "2024-04-12T21:00:00.000Z"
}

###


###

PUT {{baseUrl}}/orders/status/bd87ccf3-b3ef-468d-a29c-8d23d98c7042
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "status": "PROCESSING_ORDER"
}
###


PUT {{baseUrl}}/journey/20f20dee-21d3-4b72-8985-3d0d04cd8780
content-type: application/json

###
POST {{baseUrl}}/products
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Produto 1",
  "price": 10,
  "description": "Descrição do produto 1",
  "inStock": 19
}


###

PUT {{baseUrl}}/products/6e8d1430-b5c8-46fd-bf1d-642eeb2d3e83
Content-Type: application/json

{
  "inStock": 655
}


###

DELETE {{baseUrl}}/products/7142e8dc-98b3-4837-9855-d2f6c044fc17