name: CI

on:
    push:
        branches: [development]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout do Repositório
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20.13.0" 

            - name: clear cache
              run: npm cache clean --force
            - name: install dependencies
              run: npm install
                  
            - name: Build
              run: npm run build


            - name: Deploy 
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.DEV_SSH_HOST }}
                  username: ${{ secrets.DEV_SSH_USER }}
                  port: ${{ secrets.DEV_SSH_PORT }}
                  key: ${{ secrets.DEV_SSH_KEY }}
                  source: "., !node_modules"
                  target: "~/controle_de_ponto_jm"

            # - name: update API
            #   uses: appleboy/ssh-action@master
            #   with:
            #       host: ${{ secrets.DEV_SSH_HOST }}
            #       username: ${{ secrets.DEV_SSH_USER }}
            #       port: ${{ secrets.DEV_SSH_PORT }}
            #       key: ${{ secrets.DEV_SSH_KEY }}
            #       script: |
            #           cd "~/controle_de_ponto_jm"
            #           npm install
            #           npx prisma generate 
            #           echo "Prisma generation completed."
            #           npx prisma migrate deploy 
            #           echo "Prisma migration completed."
            #           pm2 restart point_system
