name: CI

on:
    push:
        branches: [development]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout do Repositório
              uses: actions/checkout@v4.1.7

            - name: Setup Node.js
            - uses: actions/setup-node@v4
              with:
                node-version: 18

            - name: Clean Node.js Cache
              run: npm cache clean --force

            - name: Remove package-lock.json
              run: rm -f package-lock.json

            - name: Install Yarn
              run: npm install -g yarn

            - name: Install Dependencies
              run: yarn install --ignore-engines
                  
            - name: Build
              run: npm run build

            - name: Test SSH Connection
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.DEV_SSH_HOST }}
                username: ${{ secrets.DEV_SSH_USER }}
                port: ${{ secrets.DEV_SSH_PORT }}
                key: ${{ secrets.DEV_SSH_KEY }}
                script: |
                  echo "SSH connection successful."

            - name: Deploy 
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.DEV_SSH_HOST }}
                  username: ${{ secrets.DEV_SSH_USER }}
                  port: ${{ secrets.DEV_SSH_PORT }}
                  key: ${{ secrets.DEV_SSH_KEY }}
                  source: "., !node_modules"
                  target: "~/controle_de_ponto_jm"

            - name: Update API
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.DEV_SSH_HOST }}
                  username: ${{ secrets.DEV_SSH_USER }}
                  port: ${{ secrets.DEV_SSH_PORT }}
                  key: ${{ secrets.DEV_SSH_KEY }}
                  script: |
                      cd "~/controle_de_ponto_jm"
                      npm install
                      npx prisma generate 
                      echo "Prisma generation completed."
                      npx prisma migrate deploy 
                      echo "Prisma migration completed."
                      pm2 restart point_system
